### ISSUE TITLE
怎么扫码？

### ISSUE THREAD

**Issue by 28554010** [fuck-xuexiqiangguo/docker#1]
docker没有图形界面怎么扫码？

**Comment by Fxxk-XueXiQiangGuo** [comment]
二维码是直接显示在命令行界面的

![](https://user-images.githubusercontent.com/48042037/53690893-1cfcaa00-3d41-11e9-9254-58926fcfc006.png)

**Comment by 28554010** [comment]
厉害！这个真的很👍！
