### ISSUE TITLE
密码登录是不是失效了

### ISSUE THREAD

**Issue by edwardmjc** [fuck-xuexiqiangguo/docker#13]
改了script, cp进去了, 然而执行后log很少, 没有在学. 去掉密码选项, 扫码学习一切正常.

**Comment by wenbochang888** [comment]
你用浏览器登陆一下。已经没有用户名密码的选项了。接口直接给屏蔽了

**Comment by edwardmjc** [comment]
> 你用浏览器登陆一下。已经没有用户名密码的选项了。接口直接给屏蔽了

win版还可以, 但是有的时候会出验证码

**Comment by Fxxk-XueXiQiangGuo** [comment]
现在用用户名密码登录都是需要验证码的。
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#080---2019-07-16)。

**Comment by Fxxk-XueXiQiangGuo** [comment]
> 你用浏览器登陆一下。已经没有用户名密码的选项了。接口直接给屏蔽了

用户名密码登录的选项从一开始就是没有的。是我查文档找到接口，自己加链接上去的。

**Comment by wenbochang888** [comment]
感谢贡献
