### ISSUE TITLE
每天都要登录服务器手动扫码登录

### ISSUE THREAD

**Issue by ghost** [fuck-xuexiqiangguo/docker#14]
自从用户名密码登录失效后，每天都要登录服务器扫码登录，这和本地开个客户端效率差不多了。有没有办法不必每天登录？

**Comment by Fxxk-XueXiQiangGuo** [comment]
[已经更新](https://github.com/fuck-xuexiqiangguo/Fuck-XueXiQiangGuo/blob/master/CHANGELOG.md#080---2019-07-16)。
