### ISSUE TITLE
我有很多错误

### ISSUE THREAD

**Issue by lgxlyh** [fuck-xuexiqiangguo/docker#7]
2019/4/23 13:48:11 今日积分: 24 总积分: 1378 阅读文章积分: 6 / 6 观看视频积分: 6 / 6 文章时长积分: 6 / 6 视频时长积分: 5 / 6
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default

**Comment by neworcer** [comment]
跟我的一摸一样。你的可以挂着每天自动刷分吗？

**Comment by lgxlyh** [comment]
可以用,偶尔剩几分就不行。发这条消息时就是剩下的分没有变化,以为是出错

**Comment by lbbboy** [comment]
我在VPS上，也是这么多错误。还不能用，第一次运行不会出二维码，停止重启后有二维码，但是几秒容器就自己停止了。

**Comment by lgxnas** [comment]
github上更新app.asar经常连接失败,换成gitee了

**Comment by lgxlyh** [comment]
> github上更新app.asar经常连接失败,换成gitee了
